### PR TITLE
Make the PEM Signing Keys Optional

### LINKED ISSUE #3: Only use the TokenReview API when validating service account tokens.
Not all Kubernetes users have access to the service account signing public key so this auth backend cannot be used in those cases. One solution is to force users of this auth backend to obtain the signing keys required for validation.

Another solution, which maybe more correct, is to avoid doing any extra validation outside of the Kubernetes TokenReview API.

### PR DESCRIPTION
**Pull request by briankassouf**
fixes #3

### CODE REVIEW

**Comment by brunomcustodio** [comment]
@briankassouf I am getting the same error as @kelseyhightower in Kubernetes 1.7.5 (GKE, RBAC-enabled). Do you have any clues as to what may be causing it?

**Comment by brunomcustodio** [comment]
@briankassouf I ran

```bash
curl https://my-vault.example.com/v1/auth/kubernetes/login -d '{"jwt":"eyJ(...)L4A","role":"demo"}'
```

on a pod running using a `my-pod-account` service account in the `default` namespace and got the following log entries on the `apiserver` logs:

```text
I0921 14:11:10.550909       5 rbac.go:114] RBAC DENY: user "system:serviceaccount:default:my-pod-account" groups ["system:serviceaccounts" "system:serviceaccounts:default" "system:authenticated"] cannot "create" resource "tokenreviews.authentication.k8s.io" cluster-wide
I0921 14:11:10.551011       5 wrap.go:42] POST /apis/authentication.k8s.io/v1/tokenreviews: (1.354755ms) 404 [[Go-http-client/1.1] 35.197.223.167:59958]
```

Here's my `ClusterRoleBinding` (Vault runs using a `vault` service account on namespace `vault`):

```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault
  namespace: vault
```

Could you please help me figure out what is going wrong?

**Comment by jefferai** [comment]
I believe, but am not authoritative, that the API needed for token review is not in GKE yet but will be soon. This may only work with standalone Kube for the moment. (GKE lags a little.)

**Comment by karabijavad** [comment]
@jefferai im having this problem too. do you know which version of kubernetes contains the needed API?

**Comment by karabijavad** [comment]
ok i think i found whats happening.

@jefferai if you look here:
https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/master/token_review.go#L76
you will see that the vault plugin attempts to access /apis/authentication.k8s.io/v1/tokenreviews

but it seems that, even in gke kubernetes 1.7.6, authentication.k8s.io is not available under apis.

here is the output of what is available to me when i hit /apis/, when authenticated. notice that "authentication" is nowhere to be found

curl $APISERVER/apis/ --header "Authorization: Bearer $TOKEN" --insecure
```
{
  "kind": "APIGroupList",
  "apiVersion": "v1",
  "groups": [
    {
      "name": "apiregistration.k8s.io",
      "versions": [
        {
          "groupVersion": "apiregistration.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "apiregistration.k8s.io/v1beta1",
        "version": "v1beta1"
      },
      "serverAddressByClientCIDRs": null
    },
    {
      "name": "extensions",
      "versions": [
        {
          "groupVersion": "extensions/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "extensions/v1beta1",
        "version": "v1beta1"
      },
      "serverAddressByClientCIDRs": null
    },
    {
      "name": "apps",
      "versions": [
        {
          "groupVersion": "apps/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "apps/v1beta1",
        "version": "v1beta1"
      },
      "serverAddressByClientCIDRs": null
    },
    {
      "name": "authorization.k8s.io",
      "versions": [
        {
          "groupVersion": "authorization.k8s.io/v1",
          "version": "v1"
        },
        {
          "groupVersion": "authorization.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "authorization.k8s.io/v1",
        "version": "v1"
      },
      "serverAddressByClientCIDRs": null
    },
    {
      "name": "autoscaling",
      "versions": [
        {
          "groupVersion": "autoscaling/v1",
          "version": "v1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "autoscaling/v1",
        "version": "v1"
      },
      "serverAddressByClientCIDRs": null
    },
    {
      "name": "batch",
      "versions": [
        {
          "groupVersion": "batch/v1",
          "version": "v1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "batch/v1",
        "version": "v1"
      },
      "serverAddressByClientCIDRs": null
    },
    {
      "name": "certificates.k8s.io",
      "versions": [
        {
          "groupVersion": "certificates.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "certificates.k8s.io/v1beta1",
        "version": "v1beta1"
      },
      "serverAddressByClientCIDRs": null
    },
    {
      "name": "networking.k8s.io",
      "versions": [
        {
          "groupVersion": "networking.k8s.io/v1",
          "version": "v1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "networking.k8s.io/v1",
        "version": "v1"
      },
      "serverAddressByClientCIDRs": null
    },
    {
      "name": "policy",
      "versions": [
        {
          "groupVersion": "policy/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "policy/v1beta1",
        "version": "v1beta1"
      },
      "serverAddressByClientCIDRs": null
    },
    {
      "name": "rbac.authorization.k8s.io",
      "versions": [
        {
          "groupVersion": "rbac.authorization.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "rbac.authorization.k8s.io/v1beta1",
        "version": "v1beta1"
      },
      "serverAddressByClientCIDRs": null
    },
    {
      "name": "storage.k8s.io",
      "versions": [
        {
          "groupVersion": "storage.k8s.io/v1",
          "version": "v1"
        },
        {
          "groupVersion": "storage.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "storage.k8s.io/v1",
        "version": "v1"
      },
      "serverAddressByClientCIDRs": null
    },
    {
      "name": "apiextensions.k8s.io",
      "versions": [
        {
          "groupVersion": "apiextensions.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "apiextensions.k8s.io/v1beta1",
        "version": "v1beta1"
      },
      "serverAddressByClientCIDRs": null
    }
  ]
}
```

**Comment by jefferai** [comment]
Indeed, as I said, the version currently on GKE is too old.

**Comment by karabijavad** [comment]
@jefferai ahh, ok, im starting to understand now.

so, with a kubernetes version that does not include the authentication/tokenreview support (e.g. < 1.8) one would need to include the appropriate certificates inside "pem_files" of the vault kube auth config, so that vault does not need to reach out to kube to verify the token.

but with 1.8, if you leave pem_files empty, it will reach out to kube to do the auth?

am i understanding correctly?

**Comment by jefferai** [comment]
@briankassouf will know more, bit I believe this simply isn't supported on pre-1.8 Kube.

**Comment by karabijavad** [comment]
@jefferai i would propose you add that to the vault kube auth backend docs (that it needs 1.8+/tokenreview api support)
:)
not trying to come off rude, but it would have saved me a lot of time and research if i had known this. alot of people out there are probably trying to install the vault-kube stuff on their gke environments (since its really exciting stuff!)

**Comment by jefferai** [comment]
@karabijavad we weren't aware of this limitation with GKE until post-release.

**Comment by karabijavad** [comment]
@jefferai totally understand! i appreciate the work youre doing and love the product. i do not mean to sound upset. to be honest, i learned alot about kubernetes and vault in the process of trying to get this integration to work, so thats a plus! :)

just trying to provide some input from the perspective of a user, albeit a new one

also, it might be helpful in the docs to explain the pem_keys=@signingkey.crt kubernetes_ca_cert=@ca.crt. i do not see a mention of what signingkey.crt and ca.crt are supposed to be. perhaps this is obvious to someone who has done a manual kube install, and needed to generate these keys, but in an automated installation this is not apparent to me

again, thanks for what y'all are doing. just figured id toss in my two cents in case its any use to y'all!

**Comment by jefferai** [comment]
@karabijavad Yep, we'll be adding to the docs with more info -- @briankassouf is I think out yesterday and today and knows the most about all of the current state so when he's around he'll get some docs fixed up

**Comment by karabijavad** [comment]
@jefferai awesome.
for what its worth, i got it working by simply doing a manual install of the latest kubernetes. working totally fine.

im just confused about the intended flow. 
is the idea that there would just be the one vault-auth service account, which any pod that needs to talk to auth would use?

or, is the idea that each of your deployments/pods would have its own serviceaccount, and one would need to make a vault role for each, and bind that vault role to the serviceaccount name?

i think @kelseyhightower mentioned in some other issue somewhere, the idea of a single sa for vault.
i guess this coulld be accomplished by bound_service_account_names=sa-1,sa-2,sa-3 ?

**Pull request merged**
