### PR TITLE
Allow annotating service accounts with arbitrary tags for policy templating

### PR DESCRIPTION
**Pull request by dovys**
Addresses [hashicorp#85](https://github.com/hashicorp/vault-plugin-auth-kubernetes/issues/85)

We took Mark's proposed design and added support for defining annotations on service accounts that can later on be used in policy templating.

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-account
  namespace: default
  annotations:
    auth-metadata.vault.hashicorp.com/service-role: example-value
```

Which you can then use in policies as so
```
{{identity.entity.aliases.${vault_auth_backend.kubernetes.accessor}.metadata.service_role}}
```

**Who the change affects or is for (stakeholders)?**
The change is behind a config flag called `enable_custom_metadata_from_annotations` so it should not affect any of the existing integrations.
In order to enable the flag users will have to update the clusterrole and allow Vault to read service accounts. If this change is accepted we'll open PRs to update various docs, terraform providers, etc.
This will also introduce another roundtrip to the Kubernetes API, however we are using a pooled tcp client so hopefully not too many new open connections.

**Why is the change needed?**
At @monzo we want to use fully qualified service names for certificates issued under Vault's PKI, ie `service.profile`. At the same time we want policies and roles to be very strict so `service.profile` is not allowed to obtain certificates for `service.id`. As we have over 2000 microservices and they grow at a steady rate it's not feasible to write a new policy for each. Allowing us to annotate service accounts with the fully qualified service name and then use it in PKI mount allowed_domains with templating solves this issue.

# Design of Change
We've largely adhered to the current code style present in the repo. 
All changes are behind a config flag `enable_custom_metadata_from_annotations`. Existing integrations are not affected until the flag is turned on.

# Related Issues/Pull Requests
**TBD** - we'll create PRs for the terraform provider and docs when this PR has been largely agreed upon

# Contributor Checklist
- [ ] **TBD** Add relevant docs to upstream Vault repository, or sufficient reasoning why docs won’t be added yet
[My Docs PR Link](link)
[Example](https://github.com/hashicorp/vault/commit/2715f5cec982aabc7b7a6ae878c547f6f475bba6)
- [x] Add output for any tests not ran in CI to the PR description (eg, acceptance tests)
- [x] Backwards compatible

### CODE REVIEW

**Comment by tomhjp** [comment]
Hi @dovys, thanks for raising this! I'm going to gather some feedback internally on the feature, and I'll get back to you as soon as I can.

**Comment by CodyKurtz** [comment]
Is there an update on this?

**Comment by CodyKurtz** [comment]
> Hi @dovys, thanks for raising this! I'm going to gather some feedback internally on the feature, and I'll get back to you as soon as I can.

Any updates on this? Thank you

**Comment by thyton** [comment]
Thank you for your contribution, @dovys! We started a fresh PR #226 taking inspiration from this one. We're going to close your PR.

**Comment by thyton** [comment]
Thank you for your contribution, @dovys! We started a fresh PR https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/226 taking inspiration from this one. We're going to close your PR.

**Pull request closed without merging**
